Created initial structure for a fake libxcb-randr.so
This currently does nothing, it's just an empty wrapper around
libxcb-randr. This is work in progress on bug #16.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -55,6 +55,19 @@ if [ -z "${FAKE_LIBRARY_DIRECTORY}" ]; then
 fi
 echo "The fake library will be installed to ${FAKE_LIBRARY_DIRECTORY}"
 
+XCB_LINE=
+if pkg-config --exists xcb-randr; then
+	echo "xcb-randr is available; also building xcb interface"
+
+	REAL_XCB_RANDR_LIBRARY=$(find /usr/lib -name libxcb-randr.so | head -n 1)
+	if [ -z ${REAL_XCB_RANDR_LIBRARY} ]; then
+		echo "          Aborting: Did not find libxcb-randr.so in /usr/lib"
+		exit 1
+	fi
+	echo "The path to the real libxcb-randr library is ${REAL_XCB_RANDR_LIBRARY}"
+	XCB_LINE="#define REAL_XCB_RANDR_LIB \"${REAL_XCB_RANDR_LIBRARY}\""
+fi
+
 cat > config.h <<EOF
 /* This file was automatically generated by ./configure */
 
@@ -64,6 +77,7 @@ cat > config.h <<EOF
 
 #define REAL_XRANDR_LIB "${REAL_LIBRARY}"
 #define FAKEXRANDR_INSTALL_DIR "${FAKE_LIBRARY_DIRECTORY}"
+${XCB_LINE}
 EOF
 
 exit 0
